### ISSUE TITLE
UtilityFunction on global methods outside a class

### ISSUE THREAD

**Issue by adrianbn** [troessner/reek#1024]
Reek is reporting UtilityFunction on `global_bar` in the following code:
```ruby
module Foo
  class Bar
    include Singleton

    def initialize
    end

  end
end

def global_bar
  Foo::Bar.instance
end
```

According to the docs `is any instance method that has no dependency on the state of the instance.`, but `global_bar` is technically not an instance method, is it? If reek is right reporting this, what would be a better way to achieve the same API convenience?

Thanks!

**Comment by troessner** [comment]
>> According to the docs is any instance method that has no dependency on the state of the instance., but global_bar is technically not an instance method, is it?

It is ;)

>>
( $ ) pry
[1] pry(main)> p self
main
=> main
[2] pry(main)> p self.class
Object
=> Object
[3] pry(main)> def omg; end
=> :omg
[4] pry(main)> method(:omg).owner
=> Object
[5] pry(main)> Object.instance_methods.grep /omg/
=> [:omg]

I believe there are no global methods in Ruby.

**Comment by adrianbn** [comment]
Oh, right. I wasn't expecting Reek to take into account anything outside my code; i.e. it doesn't belong to any of my classes so I thought I was good. That makes sense. Is there a better way to achieve the same functionality without tripping Reek? I'm using this for things like a logger or a config instance that I would like to be global singletons. 

Thanks!

**Comment by mvz** [comment]
There are several options you could try:
* Use `Foo::Bar.instance` directly, if you never want to use a different object. This is the essence of the Singleton pattern.
* Use a constant instead of a method.
* Use some sort of dependency injection like `dry-container`. I *think* this will give you methods like the ones you want, but I haven't used it.
* Create a module and define methods using `module_function`. You can then include that module in your classes and use the methods directly, or call those methods on the module (e.g., `MySingletons.the_logger`). Reek will not mark module functions as Utility Functions.

**Comment by adrianbn** [comment]
Thanks @mvz; I think the most appealing way to me would be to define a companion module to my class that uses `module_function` to expose the interface I'm after. I'll close this issue since it was my bad :)
