### ISSUE TITLE
Introduce rubocop-rspec

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1036]
@backus nudged me regarding [rubocop-rspec](https://github.com/nevir/rubocop-rspec) - looks interesting and relevant for us. Let's give it a shot - wdyt?

**Comment by backus** [comment]
Happy to help with the decision and with introducing the gem. Just like rubocop there is a lot of configuration options and features that can be overwhelming at first but over time help you strongly calibrate your preferences. I'm also looking for feedback on how the gem can be improved further (I've been acting as the primary maintainer for the last month or so).

**Comment by backus** [comment]
See the build for https://github.com/troessner/reek/pull/1037 to see what is flagged. Most obvious cop I expect you would disable is the `ExpectActual` cop since right now your rspec matcher basically makes it impossible to avoid this. Basically this cop says that you should not say `expect([LITERAL]).to ...` instead you should have `expect([thing under test]).to ...` but the `reek_of` matcher forces a literal into `expect(...)`

**Comment by mvz** [comment]
@backus thanks for the demo. I can see how this will be very useful in making our specs consistent. One thing I see is that there are several cops that mention some exceeded maximum, without mentioning what the value actually is ('Maximum example group nesting exceeded', and 'Too many expectations.'). It would be useful to have the values shown, as 'Example has too many lines. [10/5]' does.

We could work around the ExpectActual issue by putting the value in a variable, but that seems like cheating. Perhaps this cop is too simplistic, since it would also flag stuff like `expect(3).to be_odd`, which seems like a sensible way to express things, and it should be limited to well-known comparison matchers, like `expect('foo').to eq thing`?

**Comment by backus** [comment]
@mvz I agree with the maximums I'm going to add an issue for that. In the meantime if you do `--auto-gen-config` it will show you what your maximum is and if you take a peek at `config/default.yml` in rubocop-rspec you can see what the default is for the gem itself

For `ExpectActual` unless you are writing specs for ruby itself (or maybe monkey patches) I'm not sure if that is actually a use case I'm worried about and I believe that cop is derived directly from an rspec guideline.

**Comment by mvz** [comment]
> For `ExpectActual` unless you are writing specs for ruby itself (or maybe monkey patches) I'm not sure if that is actually a use case I'm worried about

That makes a lot of sense, yes :smile:.

I think we should rewrite the offending examples to store the source into a variable, since it will improve readability (newlines!) and stop suggesting that reeking is a property of strings.

**Comment by mvz** [comment]
To summarize: Yes, I think we should use rubocop-rspec, and we should use most if not all of its suggestions.

**Comment by backus** [comment]
> To summarize: Yes, I think we should use rubocop-rspec, and we should use most if not all of its suggestions.

Awesome! Also, rubocop-rspec often tries to flag testing smells (which are generally indicative of code smells) so it should be up your alley. Also if you have ideas for new cops please open an issue and I'll likely implement it

**Comment by backus** [comment]
Seems like this can be closed now that #1042 is merged :tada:

**Comment by troessner** [comment]
And closed it is ;)
