### ISSUE TITLE
False positive for InstanceVariableAssumption with indirect initialization

### ISSUE THREAD

**Issue by oliverklee** [troessner/reek#1134]
We have a facade class that basically looks like this:

``` ruby
class AdminDashboard
  def initialize
    initialized_recent_items
  end

  def recent_users
    @recent_items.fetch(:user)
  end

  def initialized_recent_items
    @recent_items = {
      user: Identity::User.recent,
      workshop: Workshop::Workshop.recent,
      tag: Workshop::Tag.recent
    }
end
```

For this class, Reek complains:

InstanceVariableAssumption: Facades::AdminDashboard assumes too much for instance variable '@recent_items' [https://github.com/troessner/reek/blob/master/docs/Instance-Variable-Assumption.md]

This looks like a false positive to me as the initialize method clearly initializes the instance variable (indirectly, though). Or am I missing anything?

**Comment by mvz** [comment]
Hi @oliverklee, you are correct in that Reek does not check for any methods that are called in `#initialize` and that may set instance variables, or even `:attr_writer`s.

Due to the static nature of Reek's analysis, this is in general a very hard problem to solve, so I'm not sure we should even start.

One could also argue that this kind of indirection makes the code less clear, so the fact that it confuses Reek indicates that improvements could be made.

Based on the code above, I would recommend moving the assignment out of `#initialized_recent_items` into the initializer. That's assuming `#initialized_recent_items` is only ever called from the initializer. For me, this improves the clarity a lot by making the initialization more explicit.

Another solution is to use lazy initialization like so:
```ruby
class AdminDashboard
  def recent_users
    recent_items.fetch(:user)
  end

  def recent_items
    @recent_items ||= {
      user: Identity::User.recent,
      workshop: Workshop::Workshop.recent,
      tag: Workshop::Tag.recent
    }
  end
end
```

**Comment by troessner** [comment]
I agree with @mvz on this, what Reek is doing here is not optimal but when you defer initialization of ivars in the initializer to a method call this hints at bigger problems in your codebase. 
That would be a smell though for which we have no detector yet. The DeferredInitialization smell ;)

**Comment by troessner** [comment]
Closing this one.
