### ISSUE TITLE
reek should look for a config on a super level

### ISSUE THREAD

**Issue by abacha** [troessner/reek#1243]
I have lots of projects that share the same reek config file, it would be nice if I could unify the lookout dir.
Like rubocop, if it didnt find a 'config.reek' on the project file, it should look for it on the home user directory

**Comment by mvz** [comment]
Reek already looks in ancestor directories and in home: https://github.com/troessner/reek#configuration-file. Or do you mean something else?

**Comment by abacha** [comment]
oh, exactly that
sorry

**Comment by dansdantas** [comment]
@mvz I don't know if it is related to this issue but on my config, reek it is not looking for ancestor configs.

I followed these steps:

> new empty project using ruby 2.4.3 and rails 5.1.4
> put reek on gemfile `version: 4.7.3`

When i am on project root with this configuration
```
"config/":
  IrresponsibleModule:
    enabled: false
```

I have no errors or warnings running `reek config/application.rb`
```
 example (master) ✗ reek config/application.rb
 Inspecting 1 file(s):
 .
```

But if i go inside config directory, it show an error using same command `reek application.rb`
```
 config (master) ✗ reek application.rb
 Inspecting 1 file(s):
 S

 application.rb -- 1 warning:
[10]:IrresponsibleModule: Example::Application has no descriptive comment [https://github.com/troessner/reek/blob/master/docs/Irresponsible-Module.md]
```
Am i doing something wrong?

**Comment by troessner** [comment]
Could it be that you have a reek configuration in the config/ directory?

**Comment by dansdantas** [comment]
No. My reek files are only on project root.

**Comment by mvz** [comment]
Perhaps there's something wrong with how Reek evaluates that "config/" path. Looks like a different issue in any case. Can you open a new ticket for this, @dansdantas?

**Comment by dansdantas** [comment]
@mvz I think i already know what is happening. It is an error on my configuration.
As stated above it says that a `config` directory should ignore that rule:
```
"config/":
  IrresponsibleModule:
    enabled: false
```

This works correctly for at project root level because it finds the directory. But when i run at child level, for obvious reasons, the said directory does not exists(i am already inside that directory). I probably should use a different way to handle several files or directories.
Sorry for wasting your time.

Just for further explanation on my problem, if anyone cares, i use neovim as my editor with ale as plugin. Everytime i open, save or edit, it runs reek for my current file. But it runs at directory level, not project root level.

**Comment by mvz** [comment]
@dansdantas yes, that is probably what is happening, but I think Reek should still handle that case correctly and should probably resolve relative file paths from the location of the config file.

**Comment by troessner** [comment]
>> but I think Reek should still handle that case correctly and should probably resolve relative file paths from the location of the config file

Couldnt agree more.
