### ISSUE TITLE
When erroring out because of an invalid byte-sequence, reek doesn't show what file it crashed on.

### ISSUE THREAD

**Issue by KurtRMueller** [troessner/reek#1262]
```
reek -ns

Inspecting 183 file(s):
SSSSSS....SS.....SSSS.S..SS.SSS..S./usr/local/bundle/gems/parser-2.4.0.0/lib/parser/source/buffer.rb:164:in `source=': invalid byte sequence in US-ASCII (EncodingError)
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/source/source_code.rb:99:in `parse'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/source/source_code.rb:33:in `initialize'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/source/source_code.rb:50:in `new'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/source/source_code.rb:50:in `from'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/examiner.rb:40:in `initialize'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:26:in `new'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:26:in `block in populate_reporter_with_smells'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:25:in `each'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:25:in `populate_reporter_with_smells'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:17:in `execute'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/application.rb:29:in `execute'
	from /usr/local/bundle/gems/reek-4.7.2/bin/reek:14:in `<top (required)>'
	from /usr/local/bundle/bin/reek:17:in `load'
	from /usr/local/bundle/bin/reek:17:in `<main>'
```

I would love it if reek told me what file it crashed on.

Anyway, thanks for all the hard work you do. Let me know if you need any info from me.

**Comment by troessner** [comment]
Interesting, thanks for the report.
`Examiners` do have some extensive error handling as you can see in [Examiner#run](https://github.com/troessner/reek/blob/master/lib/reek/examiner.rb#L99) and [Examiner#examine_tree](https://github.com/troessner/reek/blob/master/lib/reek/examiner.rb#L116) but in this case the big bang happens in the constructor [here](https://github.com/troessner/reek/blob/master/lib/reek/examiner.rb#L40) which we so far assumed to be save.

Ideally we would handle this problem in the constructor. This would scatter our error handling a bit across the class but I think in this case this is warranted since the ways errors can happen are very different. @mvz wdyt?

**Comment by mvz** [comment]
Ah yes, we're basically assuming the parsing etc. is safe, and only handling errors in the detectors.

Maybe we can add error handling for this kind of problem to `SourceCode.from`? That class is where we handle syntax errors as well.

**Comment by troessner** [comment]
Hmm, how about something like this in `SourceCode#parse`: 

```Ruby
def parse(parser, source)
  begin
    buffer = Parser::Source::Buffer.new(origin, 1)
    buffer.source = source
  rescue EncodingError => exception
    raise Errors::IncomprehensibleSourceError, origin: source.origin, original_exception: exception
  end
  # Rest stays as before
  begin
    ast, comments = parser.parse_with_comments(buffer)
```

What's missing is implementing Errors::IncomprehensibleSourceError analogous to Errors::IncomprehensibleSourceError and add some specs.

WDYT?
