### ISSUE TITLE
GraphQL Ruby default code nil-check.

### ISSUE THREAD

**Issue by johnunclesam** [troessner/reek#1276]
With the amazing graphql-ruby gem I got this code:

```ruby
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end
```

One of the problem is the `nil-check`.

Ho can I fix this?

Maybe I can also PR solution to this amazing gem.

**Comment by mvz** [comment]
This is a complex method with several problems, but I will focus on the nil check for now. It seems the purpose here is to handle the case when the client request does not pass any `variables` value. You could either decide not to call `#ensure_hash` in that case, or you could create a guard clause at the very top of the method:

```ruby
return {} unless ambiguous_param
```

Since this generated method is always the same, it would make the most sense to me for it to simply be a part of the gem rather than be generated each time.

**Comment by johnunclesam** [comment]
Yes, we should create a PR.
