### ISSUE TITLE
Inconsistent reporting for FeatureEnvy

### ISSUE THREAD

**Issue by klobuczek** [troessner/reek#1337]
The following code 
```
class << self
  def normalize_path(scope, path)
    path_desc = new(scope)
    path_desc.increment(path.shift) while path_desc.next? && path.present?
    path_desc if path.empty?
  end
end
```
raises `JsonapiExt::Scoping::Include::PathDescriptor#normalize_path refers to 'path' more than self (maybe move it to another class?)`

however, if I rewrite it to:
```
def self.normalize_path(scope, path)
  path_desc = new(scope)
  path_desc.increment(path.shift) while path_desc.next? && path.present?
  path_desc if path.empty?
end
```
it does not.

**Comment by mvz** [comment]
I've looked into this and it's super easy to make this consistent. The change doesn't even break any of our tests, which shows that we completely missed this :laughing:.

**Comment by mvz** [comment]
@pardaloupa AIUI, `private_class_method` doesn't work without arguments.

**Comment by pardaloupa** [comment]
I am really confused on how to use module_function with private class methods.

This [comment](https://github.com/janlelis/idiosyncratic-ruby.com/commit/7923275d6bfce595c3f0a0f1d9eceaa6dae43800#commitcomment-26135703) clears things up  by using extending self / private combo instead of module_function and private_class_method but goes against the ruby style [guideline](https://github.com/rubocop-hq/ruby-style-guide#module-function)... Not sure if it is a reek problem now... Any suggestions would be highly appreciated.

**Comment by mvz** [comment]
> If that is right, reek still complains

Ok, now that is a valid bug :laughing:.

**Comment by pardaloupa** [comment]
Great thanks for confirming it @mvz then I guess I will keep using module_function and private_class_method and the reek issues will vanish once a bug fix is pushed. Let me know if you need me to open a new issue as this is hard to track :+1:

**Comment by mvz** [comment]
@pardaloupa yes if you could open a new issue with your example code that would be great!

**Comment by pardaloupa** [comment]
@mvz done #1397 :+1:
