### ISSUE TITLE
AttrasgnNode is an unused extension module

### ISSUE THREAD

**Issue by siman-man** [troessner/reek#1442]
Parser::AST::Node is not supported `attrasgn` type. (It seems to be `ruby_parser` node type) - reek have used `ruby_parser` before v1.5.0. https://github.com/troessner/reek/blob/v1.4.0/reek.gemspec#L33

`LitNode` too. (maybe)

**Comment by pocke** [comment]
Thank you for your report!

I think we can also remove LambdaNode and LitNode (mentioned you also:smile:)

**Comment by pocke** [comment]
Sorry forget my comment. Because we cannnot remove LambdaNode. We specify `emit_lambda` option, and it makes parser parsing `->{}` as a lambda node. Without this option, `-> {}` is parsed as a send node.
https://github.com/troessner/reek/blob/2dd52a4a72675e6848764851704498a3d592991b/lib/reek/source/source_code.rb#L10

**Comment by troessner** [comment]
Thank you for this report @siman-man, a very astute observation! How did you stumble across this?

**Comment by troessner** [comment]
Beautiful detective work :heart:
