### ISSUE TITLE
Private method not used in class

### ISSUE THREAD

**Issue by mvz** [troessner/reek#146]
In general, unused methods are bad. Unused public methods should probably be caught by test coverage, but in Ruby, private methods can be created and then used only in subclasses.

One particular case is what I see as the inverse of the Template Method pattern: The base class implements some private methods, which are used by each subclass to implement public methods. This easily becomes very unwieldy, and it is better to replace this with an implementation that does not use inheritence.

**Comment by troessner** [comment]
Actually this should be rather straightforward to implement by inspecting if the enclosing code contexts ever call the private method, shouldn't it?
No need to even look at test coverage and so, this is something we can implement right away.
Regarding the general "UnusedCode" smell i don't think this is possible with the current reek set up since  we treat every file separately, so there's no way of knowing if a public method is used somewhere else or not.

**Comment by troessner** [comment]
That came out misleading:

>> Actually this should be rather straightforward to implement by inspecting if the enclosing code contexts ever call the private method, shouldn't it?

This would then of course raise false alarms when using patterns like the template pattern you mentioned above. I'm just not sure if going with "test coverage" would work as well.

I think this whole feature is not possible in a sane way the way reek is set up right now with detecting smells on a file level base.

What do you think?

**Comment by mvz** [comment]
> This would then of course raise false alarms when using patterns like the template pattern you mentioned above.

I think I actually want it to raise an alarm in such cases.  I've fallen into the trap of creating such 'toolkit' private methods to be used by subclasses several times, and it becomes unmaintainable very quickly. I now believe such methods should be moved elsewhere and become public so they can be tested.

**Comment by troessner** [comment]
Ok, so let's say, we, the maintainers of `reek `, agree on that this:

>>  I've fallen into the trap of creating such 'toolkit' private methods to be used by subclasses several times, and it becomes unmaintainable very quickly.

is a smell (with which I kind of agree) and we want to mark it correspondingly.
For this to test we don't need to look for test coverage or anything like that, we can just do what I suggested above:

>> Actually this should be rather straightforward to implement by inspecting if the enclosing code contexts ever call the private method, shouldn't it?

Or am I missing something?

**Comment by mvz** [comment]
> Or am I missing something?

No, I agree with you completely that this should not be too difficult to implement.

**Comment by chastell** [comment]
I agree on making unused private methods a smell.

On the topic of public method usage, maybe [debride](https://github.com/seattlerb/debride) is worth taking a look at?

**Comment by troessner** [comment]
>> On the topic of public method usage, maybe debride is worth taking a look at?

Wow, seattlerb is really absurdly productive. Very impressive and inspiring.

**Comment by mvz** [comment]
> On the topic of public method usage, maybe debride is worth taking a look at?

Oh, I'm definitely going to take a look.

**Comment by troessner** [comment]
@nTraum you wanted to take a shot at this, right?

**Comment by nTraum** [comment]
Yeeep, will try to come up with something this week.

**Comment by troessner** [comment]
@nTraum you could start out like this:

- Make sure that we all agree on the scope of this feature. Especially the template pattern case from above is something where we should be clear about what constitutes a smell and what not (that we don't recognize the template pattern properly because reek works on file-base is something that shouldnt matter now)
- Get familiar with a couple of simple smells in here: https://github.com/troessner/reek/tree/master/lib/reek/smells
- Create a dummy smell based on our conceptually most simple SmellDetector, ModuleInitialize: https://github.com/troessner/reek/blob/master/lib/reek/smells/module_initialize.rb
- Create specs like this:

```Ruby
context 'private methods unused' do
  it 'reeks' do
    src = <<-EOF
      class Klass
        private
        def unused; end
      end
     expect(source).to reek_of(:UnusedPrivateMethod, { name: 'unused' })
```

And whoopsie, I just realized that this thing might be slightly more complicated than we thought because you also need to track the visibility of where you are at since there could be code like this:

```Ruby
class Klazz
  private
  def omg; end
  public
  def holla_die; end
  private
  def waldfee; end
  public
  def hossa; end
  private :hossa
end
```

But let's get a first draft up and not worry about tracking of visibility.:)

**Comment by mvz** [comment]
Your method contexts will know their own visibility thanks to recent changes.

**Comment by troessner** [comment]
>> Your method contexts will know their own visibility thanks to recent changes.

Ah, right!

**Comment by troessner** [comment]
Seems like we're coasting a little here - I'd like to take this over if you don't mind @ntraum

**Comment by troessner** [comment]
Preliminary PR up in #724 
I'd like to discuss the specs there so that we're all on the same page regarding our expectations.

**Comment by troessner** [comment]
#794 is merged, closing this one.
