### ISSUE TITLE
Instance Variable Assumption case

### ISSUE THREAD

**Issue by TeTiRoss** [troessner/reek#1477]
Should the code below trigger `Instance Variable Assumption` smell? 

``` ruby
def user
  return @user if defined? @user

  @user = User.find_by email: 'example@example.com'
end
```

Currently it is. Is it ok? If it is, then how should you handle case when you can't go with simple `@user ||= ...` because it can return `nil` and memoization will not work.

**Comment by troessner** [comment]
How about introducing the [Null Object Pattern](https://medium.com/@franzejr/null-object-pattern-in-ruby-12a809bc75cc)?

**Comment by TeTiRoss** [comment]
Yes, it can work as a solution in this case. But should this kind of code raise `Instance Variable Assumption` smell if it's clearly not what it is, but actually opposite. I'm not assuming that this instance variable exists, I'm checking if it is.

**Comment by troessner** [comment]
> I'm not assuming that this instance variable exists, I'm checking if it is.

Since there are many ways for checking this in Ruby Reek can't potentially catch all of them, so we're not even trying. Our smell detectors for many smells would become huge and quite unmaintainable.

From a purely rational point of view, you are right, it probably shouldn't smell with that specific smell. It probably should have some other smell though which we have not named yet ;)

**Comment by TeTiRoss** [comment]
🙂 Ok, got it. So I guess should just disable it for this particular case.

**Comment by troessner** [comment]
Yes, makes sense :)
