### ISSUE TITLE
Attribute smell

### ISSUE THREAD

**Issue by nomasprime** [troessner/reek#1569]
I get what this is saying but how is sending values to an initializer any different?

I'm using `attr_writer` to allow clients to change a cache directory, how else can I change it?

**Comment by mvz** [comment]
When you send values to an initializer you can create an object that is in effect immutable.

I can't say that much about it without seeing the code, but if you use `attr_writer` to allow clients change a cache directory, this means your object is automatically not thread-safe, since another client can set the cache directory without the first one knowing about it.

The general solution is to allow each client to create some object and pass the cache directory as a parameter.

**Comment by nomasprime** [comment]
Ah, of course. Thought it must be related to mutability, didn't see the solution for some reason.

Thank you so much @mvz 🙂
