### ISSUE TITLE
 UncommunicativeVariableName rubocop recomendation oposite to rubycritic statment

### ISSUE THREAD

**Issue by Pauloparakleto** [troessner/reek#1616]
```
def foo
      begin
        do_something_dangerous

      rescue StandardError => e
        @result = e
      end
      @result
 end
```
The rucbocop says to use the famous `e` variable representing the error while the rubycritic says to use a better variable description. The result is a ` UncommunicativeVariableName`, detailing my class with `GoodCents::ImportCsv#build has the variable 
name 'e'`

`rubocop --version 1.18.3`
`rubycritic --version 4.6.1` 

If this is the properly place to discuss it, someone needs to reproduce it as well. Thanks in advantage.

**Comment by Drenmi** [comment]
Hello! 👋 

Ruby core team member here. Since RuboCop has moved towards configurability, the default configuration shouldn't be treated as an authoritative source on what is "good". In most cases the default is arbitrarily chosen by the author of the cop.

You can configure the desired variable name in your `.rubocop.yml` like so:

```yaml
Naming/RescuedExceptionsVariableName:
  PreferredName: error
```

**Comment by chastell** [comment]
(FWIW, I have _feelings_ about just that and _much_ prefer an explicit `exception`, `error`, or at least `ex` / `err` rather than a sole `e`.)

**Comment by mvz** [comment]
I agree. @Pauloparakleto please follow @Drenmi's advice to make RuboCop and Reek work well together.

**Comment by Pauloparakleto** [comment]
Thanks you all, @mvz , @chastell and @Drenmi
