### ISSUE TITLE
.reekignore

### ISSUE THREAD

**Issue by mcandre** [troessner/reek#220]
Would be nice if reek loaded `.reekignore`, like `.gitignore` files, to help users ignore scanning certain files and directories.

**Comment by allomov** [comment]
@troessner the issue does not really answers the question "how to exclude a file". you can remove a folder with `exclude_paths`, but not a file.

**Comment by nomasprime** [comment]
Looks like reek, unlike other linters, doesn't take gitignore into account. Ignored files don't progress down the pipeline so can't think of an instance why you would want to lint them by default.

I came to this issue because reek insists on linting vendor/bundle unless I add to reek specific config. Is this an accurate reflection?

**Comment by mvz** [comment]
> I came to this issue because reek insists on linting vendor/bundle unless I add to reek specific config. Is this an accurate reflection?

Yes, this is accurate.

**Comment by nomasprime** [comment]
Thanks @mvz.
