### ISSUE TITLE
Make development calls to reek behave more sane

### ISSUE THREAD

**Issue by troessner** [troessner/reek#406]
Not sure how to phrase this properly.
We have a rather weird  "Use the local reek version when calling reek from the reek working directory. But still require reek to be installed properly" - logic in place.

One example would be #405 
Another example would be this:

In the reek working directory:
>>
  ( $ (master)) pwd
/home/timo/dev/reek

Nothing works when reek is not installed via rubygems:
>>
 ( $ (master)) reek -v
No command 'reek' found, did you mean:
 Command 'ree' from package 'ree' (universe)
reek: command not found

Ok, let's install it:
>>
  ( $ (master)) gem install reek
Fetching: reek-2.0.1.gem (100%)
Successfully installed reek-2.0.1
Parsing documentation for reek-2.0.1
Installing ri documentation for reek-2.0.1
Done installing documentation for reek after 1 seconds
1 gem installed

reek version now works:
>>
  ( $ (master)) reek -v
reek 2.0.1

which reek lists the rubygems path:
>>
  ( $ (master)) which reek
/home/timo/.rvm/gems/ruby-2.1.1/bin/reek

So let's add a raise at the beginning of bin/reek:
>>
  ( $ (master)) sed -i '1s/^/raise /' bin/reek 
{-timo-|-columbia-} => [~/dev/reek]

And there we go:
>>
  ( $ (master)) reek -v
/home/timo/dev/reek/bin/reek:1:in `<top (required)>': unhandled exception
	from /home/timo/.rvm/gems/ruby-2.1.1/bin/reek:23:in `load'
	from /home/timo/.rvm/gems/ruby-2.1.1/bin/reek:23:in `<main>'
	from /home/timo/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/timo/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'

It's great for development that a call to reek uses the local reek version if we're in that directory, but the overall behaviour is pretty weird as you can see above.
Let's discuss how can make this less insane.:)

**Comment by chastell** [comment]
Isn’t this the way RubyGems handles this nowadays? I use ruby-install + chruby + rubygems-bundler, so I have:

```
$ which reek
/home/chastell/.gem/ruby/2.2.1/bin/reek
```

…but it looks like this:

```ruby
#!/usr/bin/env ruby_executable_hooks
#
# This file was generated by RubyGems.
#
# The application 'reek' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

gem 'reek', version
load Gem.bin_path('reek', 'reek', version)
```

`Gem.bin_path` does the magic, returning in my case `/home/chastell/coding/reek/bin/reek` (which is where I have the local checkout).

**Comment by mvz** [comment]
Something strange is going on here.

**Comment by mvz** [comment]
I'm not using `rubygems-bundler` and I don't have this problem.

**Comment by chastell** [comment]
What are the contents of your `/home/timo/.rvm/gems/ruby-2.1.1/bin/reek`?

**Comment by chastell** [comment]
I think I might be onto something here: `bin/reek` (and everything else beneath) requires reek codebase via `require 'reek/…'` calls. If reek is installed as a gem, the gem’s `lib` location is found before `./lib`, and so Ruby loads the gem files before the local checkout’s.

There are two solutions to this:
* run `ruby -Ilib bin/reek` rather than `bin/reek`, or
* replace all `require 'reek/…'` calls with `require_relative '…/reek/…'` calls and then the local `bin/reek` will use the local files.

I think the latter is a better solution – I’m happy to come up with a PR that replaces all `require 'reek/…'` calls with `require_relative '…/reek/…'` (I have some of it done already).

**Comment by chastell** [comment]
(I think the latter is also beneficial to newcomers, as it makes `bin/reek` Just Work™ without them learning that they have to `ruby -Ilib bin/reek` instead.)

**Comment by mvz** [comment]
IMHO, newcomers should run `bundle exec reek`, which I think is standard for Ruby CLI dev. Alternatively, they can run `ruby -Ilib bin/reek`. Also quite standard.

Other than that, what is the problem we're trying to solve here? It seems for both of you running `reek` in the development directory will in fact magically run `bundle exec reek` due to binstubs, which will in turn automatically prepend `./lib`, so you have the development version of reek with the development version of the library. If you don't have reek installed, there is no magical binstub so you need to always do `bundle exec reek`. On the other I hand, I don't have such magical binstubs, so I run `bundle exec reek` if I want the dev version, or just `reek` if I want the known-good released version.

I don't think `require_relative` will solve much, since I'm not sure it is guaranteed to work from inside `bin/reek` once it's installed.

**Comment by mvz** [comment]
@troessner can you confirm that you also have `rubygems-bundler` installed?

**Comment by chastell** [comment]
> It seems for both of you running reek in the development directory will in fact magically run bundle exec reek due to binstubs

I don’t have binstubs (meaning ‘shims in `./bin` or ./.bin`’). All `rubygems-bundler` does it makes the gem-installed executables in `$GEM_HOME` find the executable from the gem version defined in `./Gemfile` (if there is one) rather than the executable from the newest gem (which RubyGems does by default).

`bin/reek` does not run `bundle exec reek`, it just runs whatever’s in `bin/reek` – but because RubyGems redefine `require`, `/home/chastell/.gem/ruby/2.2.1/gems/reek-2.0.2/lib` is in the `$LOAD_PATH` when `bin/reek` does `require 'reek/cli/application'` – and so it loads `/home/chastell/.gem/ruby/2.2.1/gems/reek-2.0.2/lib/reek/cli/application.rb` rather than `../lib/reek/cli/application.rb`.

Using `require_relative` means all of the reek’s pieces will refer to files from the same install location – files from gem-installed reek 2.0.2 to other files from gem-installed reek 2.0.2, files from gem-installed reek 1.6.6 to other files from gem-installed reek 1.6.6, and files from `~/coding/reek` to other files from `~/coding/reek`. :)

**Comment by mvz** [comment]
Sorry, I confused the terms. Where I said:

> It seems for both of you running reek in the development directory will in fact magically run bundle exec reek due to binstubs.

You should read:

> It seems for both of you running reek in the development directory will in fact magically run bundle exec reek due to **rubygems-bundler**.

**Comment by chastell** [comment]
Running `reek` in the development directory will run `$GEM_HOME/bin/reek` regardless of rubygems-bundler – it’s just that without rubygems-bundler it will load the `$GEM_HOME/gems/reek-2.0.3/lib` files (‘newest gem version in the system’) and with rubygems-bundler it will load the `~/coding/reek/lib` files (‘look, there’s a `Gemfile` here, let’s use it’). This is what RubyGems 2.3+ does already with `RUBYGEMS_GEMDEPS` set to `-` regardless of rubygems-bundler, but RubyGems’ parsing of `Gemfile`s is lacking in comparison to rubygems-bundler’s.

Running `bin/reek` in the development directory will indeed run `bin/reek`, but in this case `$LOAD_PATH` will include `$GEM_HOME/gems/reek-2.0.3/lib` and not `~/coding/reek/lib`, so `require 'reek/cli/application'` in `bin/reek` (and other `require 'reek/…'` calls in other places) will load the gem files rather than the local development one. This can be considered as RubyGems / rubygems-bundler inconsistency.

Either way, I do think using `require_relative` (added in Ruby 1.9) throughout the codebase would be beneficial (just to make sure `$GEM_HOME/gems/reek-2.0.3/bin/reek` loads reek 2.0.3’s codebase while `$GEM_HOME/gems/reek-2.0.2/bin/reek` loads reek 2.0.2’s codebase regardless of any `PATH` / `$LOAD_PATH` shenanigans), but I do see that the above argument is not the strongest one for that. :)

(Again, I’ll be happy to make the PR with the switch, as I did some of it already for debugging purposes.)

**Comment by mvz** [comment]
> Running reek in the development directory will run $GEM_HOME/bin/reek regardless of rubygems-bundler

As far as I understand it, @troessner's problem is that it will run `bin/reek` from the local directory instead.

**Comment by mvz** [comment]
Hm, not exactly instead, but it will end up executing `bin/reek`.

**Comment by mvz** [comment]
Anyway, I do see the value in making sure any `bin/reek` loads its related libraries.

**Comment by troessner** [comment]
Sorry for the late reply @chastell @mvz !

>> As far as I understand it, @troessner's problem is that it will run bin/reek from the local directory instead.

My problem is that right it works like "magic" and nobody is exactly sure why. I mean, this discussion is huge already..:)

>> It seems for both of you running reek in the development directory will in fact magically run bundle exec reek due to rubygems-bundler.

Ah, that sounds like a plausible explanation! But then it's still magic to me.

>> @troessner can you confirm that you also have rubygems-bundler installed?

>>   ( $ (master)) gem list | egrep "reek|rubygems"
reek (1.6.3)
rubygems-bundler (1.4.4)

Regarding:

>> Either way, I do think using require_relative (added in Ruby 1.9) throughout the codebase would be beneficial (just to make sure $GEM_HOME/gems/reek-2.0.3/bin/reek loads reek 2.0.3’s codebase while $GEM_HOME/gems/reek-2.0.2/bin/reek loads reek 2.0.2’s codebase regardless of any PATH / $LOAD_PATH shenanigans), but I do see that the above argument is not the strongest one for that. 

Why don't you think that's a strong argument? I think it is.

>> Using require_relative means all of the reek’s pieces will refer to files from the same install location – files from gem-installed reek 2.0.2 to other files from gem-installed reek 2.0.2, files from gem-installed reek 1.6.6 to other files from gem-installed reek 1.6.6, and files from ~/coding/reek to other files from ~/coding/reek. :)

Any huge disadvantages when doing this? To me this would be more transparent and thus a better solution.

**Comment by troessner** [comment]
Solved! Love it, now the behaviour actually makes sense.:)
