### ISSUE TITLE
Weird return in display_total_smell_count

### ISSUE THREAD

**Issue by tuexss** [troessner/reek#413]
In https://github.com/tuexss/reek/blob/master/lib/reek/cli/report/report.rb#L66 the displaying of the total smell count is interrupted if no examiner is present. I'd expect either to display a zero smell count, or to catch that case before calling this method.

**Comment by troessner** [comment]
Yes, good catch.;)
Let's see if we can fix this in the course of a future refactoring.

**Comment by mvz** [comment]
The purpose of this return is different: The total smell count is not displayed if there is **only one** examiner present. This is because the examiner itself will already print its own smell count.

This method may change in a future refactoring, but I don't see much wrong with it at the moment, and I don't think we should keep an issue open for it.

**Comment by troessner** [comment]
@mvz one could argue that it still should be better abstracted away because what you just said is not immediately clear from just reading this part of the code.
But i agree with "does not justify an issue", closing.

**Comment by tuexss** [comment]
Thanks for the explanation!

For UI consistency, I'd rather go for displaying it even with only one examiner, even if it is somewhat redundant, as users probably develop the habit to scan the output for the red highlighting first.

But that's arguable and really of no importance at all :)
