### ISSUE TITLE
Feature Envy reported even when it is reporting Utility Function

### ISSUE THREAD

**Issue by ashmoran** [troessner/reek#53]
For example:

    class Level1Generator
      def classes(row, col, value)
        (row == 1 || col == 1) ? %w[ header ] : [ ]
      end
    end

Gets both smells.  Surely it's not informative to report Feature Envy in this case?

**Comment by mvz** [comment]
It seems that any method that triggers UtilityFunction also triggers FeatureEnvy. Therefore, my proposal is to remove UtilityFunction entirely. We can then concentrate on making FeatureEnvy behave in the case of class or module functions (#27, #112).

**Comment by mvz** [comment]
@troessner, @chastell what do you think?

**Comment by troessner** [comment]
I can't think of a meaningful distinction between UtilityFunction and FeatureEnvy. 
So I agree, let's get rid of UtilityFunction and merge it with FeatureEnvy.

**Comment by chastell** [comment]
I think these are different with regards to suggesting ‘what should be done’ – UtilityFunction suggests ‘this does not need instance state, so maybe turn it into a class method’ while FeatureEnvy suggests ‘this might belong somewhere else entirely’. That said, the ‘make it into a class method’ suggestion is not very object-oriented (and a special case of ‘move it somewhere else’, really), so I’m for merging these two.

I wonder whether this won’t have the impact of ‘some of my methods were first and foremost UtilityFunctions (to be fixed by extracting them to the state-less, class level) and some had only FeatureEnvy; now all of them have FeatureEnvy, and a lot of them clearly belong close to where they’re used now, so I’ll better blacklist that smell entirely’, but I doubt that’s a good reason to keep UtilityFunction. :)

**Comment by troessner** [comment]
>> I think these are different with regards to suggesting ‘what should be done’ – UtilityFunction suggests ‘this does not need instance state, so maybe turn it into a class method’ while FeatureEnvy suggests ‘this might belong somewhere else entirely’.

Yes, very well put..:)

**Comment by mvz** [comment]
Fixed in #418.
