### ISSUE TITLE
FeatureEnvy threshold?

### ISSUE THREAD

**Issue by lucasmazza** [troessner/reek#558]
I have started to use reek in some of our codebases and noticed that the `FeatureEnvy` smell surfaces more often than the others, and in contexts where it seems to be considerably acceptable by many developers, like the following snippet:

```ruby
def filter_paths(paths)
  paths.select { |path| File.extname(path) == '.rb' }
end
``` 

This smell is reported with a `count` of 1, and would be interesting to configure the threshold of minimum references to consider this a real smell rather than reporting each occurrence as one. If this makes sense I can try to write a PR for this, but I might not have enough time for the following two weeks so anyone would be welcome to take a stab on this.

**Comment by mvz** [comment]
Which version of reek are you using? Reek 3.0.0 reports `UtilityFunction` for the method above. This is correct, since the method does not depend on the receiver.

**Comment by lucasmazza** [comment]
@mvz I'm using it through RubyCritic, which isn't up to date to the latest releases. Anyhow, giving how similar they are I think my threshold question applies to both smells.

**Comment by mvz** [comment]
You will find that `FeatureEnvy` is reported a lot less in reek 3, since it no longer reports it when it also reports `UtilityFunction`.

The method above refers to two external objects. Reek is suggesting you should ask yourself why `filter_paths` is defined in that particalar class, and that the design would improve by moving the method elsewhere; perhaps to `paths`, or to some `ExtensionFilter` module.

After considering this, you may still decide not to change the method: as mentioned in https://github.com/troessner/reek/blob/develop/docs/Code-Smells.md:
> Smells are indicators of where your code might be hard to read, maintain or evolve, rather than things that are specifically *wrong*.

**Comment by mvz** [comment]
I think we should not add this option at this time, since we just re-organized FeatureEnvy and UtilityFunction, and we dropped such a threshold option for UtilityFunction. I'd like to first gain a little more experience with the new status.

@troessner, @chastell, what do you think?

**Comment by chastell** [comment]
Agreed – especially that I consider the `filter_paths` example as a prime case of FeatureEnvy. :)

**Comment by troessner** [comment]
>> @troessner, @chastell, what do you think?

Yes, let's close this one.
