### ISSUE TITLE
Getting rid of YARD

### ISSUE THREAD

**Issue by troessner** [troessner/reek#578]
Coming from: https://github.com/troessner/reek/pull/575#issuecomment-118663161
makes me think that YARD is not the right tool for the job.
Do you guys agree and / or do we have an alternative for discussion?

**Comment by mvz** [comment]
I think this would be too drastic. I think YARD is a really nice documentation tool. The problem seems to be with defining our public API. When implementing that, the simplest way to me seemed to be to mark what was part of our 'private' API, but perhaps that was the wrong thing to do. I'd like to look into how other projects deal with that and see if we can find a better solution.

**Comment by troessner** [comment]
>>  I'd like to look into how other projects deal with that and see if we can find a better solution.

Looking forward to this..:)

**Comment by mvz** [comment]
One option is to add `@api public` to all classes that are part of the official API, and then put `--api public` in `.yardopts`. The reason for the latter is that YARD doesn't park the public API in its output. It only does that with the bits marked `@api private`.

Advantage: We only need to mark our public API, instead of everything that's not.

Disadvantage: It becomes difficult to output our entire documentation, since undoing the `--api public` flag is hard or impossible.

An alternative to setting `--api public` would be to create another YARD plugin that does output some text for all items that are marked `@api public`. This actually sounds like something other people might want to use.

**Comment by mvz** [comment]
The more I think about it the more I like the plugin option. It will allow us to have a nice friendly message on objects and methods that are safe to use, instead of an unpleasent message elsewhere.

**Comment by troessner** [comment]
>> Disadvantage: It becomes difficult to output our entire documentation, since undoing the --api public flag is hard or impossible.

Why would we want to output our entire documentation? I fail to see how this is relevant for any non-reek contributors and we just read the documentation when looking at the code.
What's our use case here?

**Comment by mvz** [comment]
> What's our use case here?

Mainly to allow people working on reek (like ourselves) to read the documentation in a nice format. I agree it's not a hugely important use case.

If we agree marking the public API instead of the private one is the way to go, I'll start a branch for that.

**Comment by troessner** [comment]
>> If we agree marking the public API instead of the private one is the way to go, I'll start a branch for that.

:+1: for that. @chastell ?

**Comment by chastell** [comment]
Oh sure, go ahead!

**Comment by troessner** [comment]
>> If we agree marking the public API instead of the private one is the way to go, I'll start a branch for that.

Any updates on this? Sorry for being a pain in the ass but this "api private" marker in our source code annoys me every time I see this...

**Comment by mvz** [comment]
.. and `@api private` is gone, so this can be closed.
