### ISSUE TITLE
Uninitialized IVar

### ISSUE THREAD

**Issue by mvz** [troessner/reek#632]
Follow-up from #483:

**An instance variable must at least be set in the constructor, or be accessed through a method with lazy initialization.**

Good:
```ruby
class Foo
  def initialize
    @bar = :foo
  end

  def foo?
    @bar == :foo
  end
end
```

Bad:

```ruby
class Foo
  def go_foo!
    @bar = :foo
  end

  def foo?
    @bar == :foo
  end
end
```

Good:

```ruby
class Foo
  def foo?
    bar == :foo
  end

  def bar
    @bar ||= :foo
  end
end

**Comment by troessner** [comment]
Cleaning up our issues: Linked this issue in #556 - closing this one.

**Comment by troessner** [comment]
Seems like we had a misunderstanding, re-opening, see my last comment on #633

**Comment by troessner** [comment]
Isn't this kind of expressed via #633 as well?
I'd then rather close this one. Right now it's confusing because we have 2 separate issues and this one feels like a subset #633 
I know there are some subtle differences, but I believe the user doesn't care for them that much as we apparently do :)

wdyt?

**Comment by mvz** [comment]
Yes, I agree. See also https://github.com/troessner/reek/pull/959#issuecomment-232974279 :smile:.
