### ISSUE TITLE
UncommunicativeParameterName claims to allow `accept: /<regex>/`, doesn't 

### ISSUE THREAD

**Issue by chorankates** [troessner/reek#886]
according to https://github.com/troessner/reek/blob/master/docs/Uncommunicative-Parameter-Name.md#configuration, the UncommunicativeParameterName smell should allow a specification like:

```yaml
UncommunicativeParameterName:
  accept: /^[a|b]$/
```

unfortunately, when i do that (OSX, ruby 2.0.0p481, reek-3.11), i get an error:
```
reek -c .reek ./**/*.rb
/Users/conor/.rvm/gems/ruby-2.0.0-p481/gems/reek-3.11/lib/reek/smells/uncommunicative_parameter_name.rb:64:in 
`acceptable_name?': undefined method `any?' for "/^[a|b]$/":String (NoMethodError)
```

since i just added some UncommunicativeVariableName expectations in the same way, i was a bit confused. 

i assumed that these two smells would be implemented similarly, but they are not. 

there are 2 problems as i see it:
  * the return coming out of `accept_names(context)` is not iterable, so `any?` cannot be used
  * https://github.com/troessner/reek/blob/master/lib/reek/smells/uncommunicative_parameter_name.rb#L61 explicitly calls out `accept_names` and `reject_patterns`, and then uses `==` and `match` for comparison

until i send a PR/someone else fixes this, i'm working around this problem by specifying my UncommunicativeParameterName configuration as:
```yaml
UncommunicativeParameterName:
  accept:
    - a
    - b
```

**Comment by troessner** [comment]
Thanks for the report! Looks legit to me ;)
A pull request would be highly welcome. In any case I'm confident we'll fix this rather sooner than later since it seems pretty straightforward.

**Comment by troessner** [comment]
@mvz @chastell would any of you like to tackle this? If not then I can fix it this weekend (or the next in worst case).

**Comment by chorankates** [comment]
@troessner i was going to try and get to the bottom of the issue this afternoon and then send a PR, but will happily defer to you

thanks for the product!

**Comment by troessner** [comment]
>> @troessner i was going to try and get to the bottom of the issue this afternoon and then send a PR, but will happily defer to you

Oh, don't get  me wrong please, a PR from your side would be highly appreciated ;)

**Comment by chorankates** [comment]
@troessner: i don't like it, but this fixes the problem:
```
diff --git a/lib/reek/smells/uncommunicative_parameter_name.rb b/lib/reek/smells/uncommunicative_parameter_name.rb
index 5648bb3..544b0b9 100644
--- a/lib/reek/smells/uncommunicative_parameter_name.rb
+++ b/lib/reek/smells/uncommunicative_parameter_name.rb
@@ -16,6 +16,8 @@ module Reek
     # Currently +UncommunicativeParameterName+ checks for
     # * 1-character names
     # * names ending with a number
+    # * names beginning with an underscore
+    # * names containing a capital letter (assuming camelCase)
     #
     # See {file:docs/Uncommunicative-Parameter-Name.md} for details.
     class UncommunicativeParameterName < SmellDetector
@@ -23,12 +25,12 @@ module Reek
       DEFAULT_REJECT_PATTERNS = [/^.$/, /[0-9]$/, /[A-Z]/, /^_/].freeze
 
       ACCEPT_KEY = 'accept'.freeze
-      DEFAULT_ACCEPT_NAMES = [].freeze
+      DEFAULT_ACCEPT_PATTERNS = [].freeze
 
       def self.default_config
         super.merge(
           REJECT_KEY => DEFAULT_REJECT_PATTERNS,
-          ACCEPT_KEY => DEFAULT_ACCEPT_NAMES
+          ACCEPT_KEY => DEFAULT_ACCEPT_PATTERNS
         )
       end
 
@@ -58,16 +60,16 @@ module Reek
       end
 
       def acceptable_name?(name:, context:)
-        accept_names(context).any? { |accept_name| name == accept_name } ||
-          reject_patterns(context).none? { |pattern| name.match pattern }
+        [accept_patterns(context)].flatten.any? { |pattern| name.match(pattern) } ||
+          [reject_patterns(context)].flatten.none? { |pattern| name.match(pattern) }
       end
 
       def reject_patterns(context)
         value(REJECT_KEY, context, DEFAULT_REJECT_PATTERNS)
       end
 
-      def accept_names(context)
-        value(ACCEPT_KEY, context, DEFAULT_ACCEPT_NAMES)
+      def accept_patterns(context)
+        value(ACCEPT_KEY, context, DEFAULT_ACCEPT_PATTERNS)
       end
 
       # :reek:UtilityFunction
```

with the actual change being to coerce whatever our input is into an array (well, that and switching `==` to `match)

besides being a hack, it made me think about all the other places that could possibly suffer from the same problem (user configuring the accept/reject option as a string where code is expecting an array) - what do you think of a bit of YAML schema validation that can run before (or separately) from reek itself?

**Comment by troessner** [comment]
I did a quick check with the following reek config:

```Yaml
---
UncommunicativeParameterName:
  accept: /^[holla|die]$/
UncommunicativeVariableName:
  accept: /^[holla|die]$/
UncommunicativeMethodName:
  accept: /^[holla|die]$/
UncommunicativeModuleName:
  accept: /^[holla|die]$/
```

Those are the 4 smell detectors that have an `accept` configuration.

And then for each of them:

>> bin/reek --smell UncommunicativeModuleName -c test.reek lib/reek/examiner.rb

Turns out that UncommunicativeVariableName is immune to this problem, the other 3 are not :-/

So we need to find a solution that works for all them.

What we could do:

* Ignore UncommunicativeVariableName for now. This baby needs a bigger refactoring anyways and it is not affected
* Move the "accept_names" [method](https://github.com/troessner/reek/blob/master/lib/reek/smells/uncommunicative_parameter_name.rb#L70) out of UncommunicativeParameterName, UncommunicativeModuleName and UncommunicativeMethodName into a module (they are identical right now which is bad in any case) and then patch the method in there to deal with this situation.

WDYT?

**Comment by troessner** [comment]
I thought about this some more and I basically see 3 solutions:

1.) The one I suggested above. But actually I think that's a pretty bad solution. The **actual** problem is that we don't validate / transform the configuration we get from the outside world (we do validate it, but that's only partially and erratic). Catching bad configuration that late in the SmellDetector is not a good, maintainable way to go, we should do this as early as possible:

2) Ideal world scenario: Validate all the things
  - Validate our yaml config with yaml schema (so we can even point to specific lines in the config file, something that is impossible later when it gets transformed into a hash)
  - And validate AppConfiguration separately since that might be passed via API users
  - Remove all hacks in subsequent SmellDetectors. I didn't check but I assume we have a couple of occurences

3) Validate only hashes:
  - Validate only the hash we get after loading the yaml, not the yaml itself
  - The same validation could then be used for the hash we get from api users
  - We might be able to use something like [Classy Hash](https://github.com/deseretbook/classy_hash) or similar

4) Move all validation and transformation rules into the AppConfiguration

@mvz && @chastell what do you think?

**Comment by mvz** [comment]
Here are some random thoughts, not yet settled into a coherent whole:

* Option 1 is a quick fix and may be good to get the problem at hand fixed.
* I'm not sure what YAML validation options are available. It looks like there is a gem, Kwalify, for that, but it seems unmaintained.
* Classy Hash looks great.
* Configuration can come from YAML, API calls, and code comments. Our initial validation effort should work for all three of them. I think that means option 3 or 4.
* Since our configuration is not terribly complex, I think we can get away with not having the line number in any configuration errors in the YAML. Code comments is a different case but we should have the line number at hand when we process those.

**Comment by troessner** [comment]
>> Configuration can come from YAML, API calls, and code comments. Our initial validation effort should work for all three of them.

Why? Yaml and API calls boil down to the very same hash structure, code comments are something completely different. In order to keep things simple I'd prefer to implement the validation for yaml config and api calls separately and then think about code comments..

>> Since our configuration is not terribly complex, I think we can get away with not having the line number in any configuration errors in the YAML. 

Agree.

>> Code comments is a different case but we should have the line number at hand when we process those.

Agree. This also backs my statement from above, that we should treat those validations separately because they actually are distinct.

>> Option 1 is a quick fix and may be good to get the problem at hand fixed.

I'll get something going the next days.

**Comment by chastell** [comment]
(FWIW, I agree with @mvz modulo @troessner’s caveat about splitting off comments. I also couldn’t find any schema validation tools outside the unmaintained Kwalify and Rx – which seems more alive, but I’d rather we validated the hash.)

**Comment by troessner** [comment]
Let's not hijack the bug report here but rather use a different issue, I just created #889

**Comment by mvz** [comment]
> > Our initial validation effort should work for all three of them.
> Why? 

To avoid duplication of rules. But I agree that the mechanism will probably be different, so let's see how it goes.
