### ISSUE TITLE
Let's have Reek catch all uncatched exceptions at top level

### ISSUE THREAD

**Issue by troessner** [troessner/reek#953]
Originating from #942:

Let's have Reek catch all uncatched exceptions at top level so that we can 1) debug user issues like in #942  easier and 2.) Improve overall user experience. 

I'll come up with a first suggestion of how this could look like in this PR in the next couple of days and weeks.

**Comment by mvz** [comment]
We can probably take a look at how RuboCop handles this, since they're pretty consistent about showing an error for the offending file and then continuing with the others.

**Comment by mvz** [comment]
@troessner any sneak preview of how you want to handle this?

**Comment by troessner** [comment]
So here's the idea:

### ReekException

* We have our own exception that is the **only** `RuntimeException` `Reek` should ever propagate upstream
* This will allow clients - be it CLI clients, RSpec matcher users or API users to react to `Reek` failures in a consistent, predictable way like this: "If you get a ReekException something is wrong with Reek and there's not much you can do about. So exit gracefully and report a bug"
* The `ReekException` always wraps the original exception to still allow for debugging

### Adapt all ports a client might use

Right now we have 3 integration possibilities:

* the binary that uses `CLI::Application`
* our RSpec matchers
* API users: Now that's more difficult since they could use literally everything we offer (marked "public" or not) but I think it's safe to say that the `Examiner` is the main touchpoint

Now the question becomes "How can update all of those integrations so that whatever happens the user gets back a ReekException?".

**I see 2 options:**

1.) We update every single integration option from above so that it:

* catches all exceptions < RuntimeException
* wraps them in a `ReekException`

2.) We just update the `Examiner` to do so.

(1) would be kind of bulletproof but also seems a little over the top and will also imply some slight code duplication.
(2) would not be 100% bulletproof in the sense that there might be some edge cases where a `RuntimeException` slips through that gets not wrapped into a `ReekException`. But it would be a minimal change compared to (1).

I think we should go with (2)

### SmellDetector

Problem is that `ReekException` from above won't fix it because it'll still miss the detailed information about the parsed source code that actually triggered the error.
Hence I suggest to make `SmellDetector` catch all RuntimeErrors as well and enrich them with information like "which file, which line" and so on.
It then re-raises the exception where it will be caught by the `Examiner` properly and wrapped into a `ReekException`.

WDYT?

**Comment by troessner** [comment]
First spec draft up in #971

**Comment by mvz** [comment]
I think we're trying to achieve some conflicting purposes:

* On the one hand we want to produce only ReekException, but we want to let the user differentiate between "it's Reek's fault", and "it's my fault".
* We want to just catch every exception, but we also want to have detailed information that is only available at the point of raising the original.

I also have the feeling we discussed a similar thing in #809.

I just can't seem to wrap my head around this feature: I'd like to see how we can start with something small so we can see if we're on the right track and not building a cannon to kill a mosquito. How about starting from the original problem: We have smell detectors sometimes failing for unexpected reasons, and Reek aborts. Instead, we probably want it to do one of two things:

1. Print a (detailed) error and skip that source.
2. Print a (detailed) error and skip that smell detector.

I think 1. is by far the simpler option, since 2. would mean handling any exceptions from smell detectors inside Examiner. Option 1, on the other hand, can be handled in the reporters. It would need the smell detectors to tag/wrap/enrich any exceptions they throw from `#run_for`.

**Comment by troessner** [comment]
>> I just can't seem to wrap my head around this feature: I'd like to see how we can start with something small so we can see if we're on the right track and not building a cannon to kill a mosquito. How about starting from the original problem: We have smell detectors sometimes failing for unexpected reasons, and Reek aborts.

Fair enough ;)

>>
Print a (detailed) error and skip that source.
Print a (detailed) error and skip that smell detector.

Yep, let's go with the first one.

**Comment by troessner** [comment]
Not sure when I can take a shot at this, if anybody wants to go ahead please do so.
Otherwise I'll happily do so when I find the time.

**Comment by troessner** [comment]
Closing this one in favor of #995
